apiVersion: v1
kind: BuildConfig
metadata:
  name: spark-pipeline
  labels:
    name: spark-pipeline
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node("maven") {

          stage("Configuration") {
            // maven cache configuration (change mirror host)
            sh "sed -i \"s|<!-- ### configured mirrors ### -->|<mirror><id>mirror.default</id><url>http://172.17.0.1:8765/nexus/content/groups/public/</url><mirrorOf>external:*</mirrorOf></mirror>|\" /home/jenkins/.m2/settings.xml"
          }


          stage("Checkout") {
            git url: "https://github.com/nicolaferraro/voxxed-bigdata-spark.git", branch: "master"
          }

          stage("Build") {
            sh "mvn clean install -Dfabric8.skip"
          }

          stage("Deploy to Development") {
            sh "mvn clean fabric8:deploy -DskipTests -Dfabric8.namespace=development -Dfabric8.mode=openshift"
          }

          stage("Deploy to Production") {
            input message: "Deploy to Production?"
            sh "mvn clean fabric8:deploy -DskipTests -Dfabric8.namespace=production -Dfabric8.mode=openshift"
          }

        }

